### ISSUE TITLE
there are no unittests

### ISSUE THREAD

**Issue by JensTimmerman** [hpcugent/mympingpong#1]
Someone should add some, then ping me to add a job to jenkins to run them.

**Comment by boegel** [comment]
Why don't you add some? ^_^

**Comment by JensTimmerman** [comment]
exactly.

**Comment by wpoely86** [comment]
Can be closed?

**Comment by boegel** [comment]
@wpoely86 if there are tests, yes :)

**Comment by wpoely86** [comment]
we have tests?

**Comment by JensTimmerman** [comment]
ok
