### ISSUE TITLE
mympingponganalysis on Cray

### ISSUE THREAD

**Issue by jgphpc** [hpcugent/mympingpong#14]
Hi,

I installed mympingpong/0.7.1-CrayGNU-2016.06-Python-2.7.12 on the Cray and i can produce the hdf5 file with `srun -t1 -n2 mympingpong -f $SCRATCH -i 200 -n 200` but i now have an issue with:
-  srun -t5 -n1 mympingponganalysis -f PPnid00064-002-msg0001024B-nr00200-it00200-20161014-163338.h5

because it fails in:

```
  File "/apps/brisi/UES/6.0.UP01/broadwell/easybuild/software/mympingpong/0.7.1-CrayGNU-2016.06-Python-2.7.12/lib/python2.7/site-packages/mympingpong-0.7.1-py2.7.egg/EGG-INFO/scripts/mympingponganalysis", line 310, in <module>

  File "/apps/brisi/UES/6.0.UP01/broadwell/easybuild/software/mympingpong/0.7.1-CrayGNU-2016.06-Python-2.7.12/lib/python2.7/site-packages/mympingpong-0.7.1-py2.7.egg/EGG-INFO/scripts/mympingponganalysis", line 254, in plot

  File "/apps/brisi/UES/6.0.UP01/broadwell/easybuild/software/Python/2.7.12-CrayGNU-2016.06/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/apps/brisi/UES/6.0.UP01/broadwell/easybuild/software/Python/2.7.12-CrayGNU-2016.06/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 84, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/apps/brisi/UES/6.0.UP01/broadwell/easybuild/software/Python/2.7.12-CrayGNU-2016.06/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 92, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/apps/brisi/UES/6.0.UP01/broadwell/easybuild/software/Python/2.7.12-CrayGNU-2016.06/lib/python2.7/lib-tk/Tkinter.py", line 1815, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:11.0"
```

Is there a way to build mympingponganalysis without mpi so i could run it on the login node instead of the compute node ?

jg.

**Comment by stdweird** [comment]
@jgphpc yes, i ususally just render it on my laptop. you don't need mpi at all for that part. but we'll have a look at the error.

**Comment by stdweird** [comment]
quick fix can be to clone the repo on the laptop, comment the mpi4py  requirementhttps://github.com/hpcugent/mympingpong/blob/master/setup.py#L46; and do a `python setup.py install --user`.

**Comment by jgphpc** [comment]
### 90 cores Cray XC30

![eff_90c](https://cloud.githubusercontent.com/assets/5328644/19396511/bd3bc0ba-9243-11e6-812e-d3d21238dfc5.png)
- I had to comment line 259 in mympingponganalysis.py:

```
  File "./mympingponganalysis.py", line 259, in plot
    self.addtext(self.meta, plt.subplot(gs1[0:1, 5:10]), fig1)
TypeError: addtext() takes exactly 3 arguments (4 given)
```

using `matplotlib.__version__/1.5.3`

**Comment by jgphpc** [comment]
Any suggestion for a large scale job ?

**Comment by boegel** [comment]
@jgphpc the `_tkinter` issue probably has a cause outside of `mympingpong`... Maybe your X forwarding tunnel timed out or something?

What do you mean with suggestions for a large scale job? You mean in terms of parameter settings?

**Comment by stdweird** [comment]
@jgphpc what do you mean with `90 cores`? we rarely run with more than one core per node. so unless 90cores = 90 nodes, try that first. it can be intersting to do 1 mpi task per socket or one per numa domain, too.
but to scale up to full cluster, start with one mpi task per node.

wrt parameters, you really need to increase the `-i` and `-n` so it has more statistical relevance. the pair sample plot shows too few sample per pair. increase the `-n` to `1000`, and the `-i` to something relevant, eg 5-10 times the number of tasks. but maybe do it in steps, as the total runtime will also go up.

**Comment by jgphpc** [comment]
# 1 mpi task per compute node

Thanks for the hint. The results look good:
- mympingpong --ntasks=100 --ntasks-per-node=1 -i 1000 -n 1000
  ![eff_100cn-nr01000-it1000](https://cloud.githubusercontent.com/assets/5328644/19436467/8b25db9a-9470-11e6-86a8-2bb102f4a3f7.png)
- mympingpong --ntasks=160 --ntasks-per-node=1 -i 1600 -n 2000
  ![eff_160cn-nr02000-it01600](https://cloud.githubusercontent.com/assets/5328644/19436683/ef6f784e-9471-11e6-8519-726664356118.png)

**Comment by jgphpc** [comment]
Hi,
what is the size of the message ? can you point me to the code, please ?
thanks, jg.

**Comment by stdweird** [comment]
it's 1kB by default, see https://github.com/hpcugent/mympingpong/blob/master/bin/mympingpong.py#L407 (i.e. there's a commandline option :smile: )
normally it's printed as text, but you had to comment that out.

**Comment by jgphpc** [comment]
* 1core/cnode

# 32cn 
![032-msg0001024b-nr00200-it00010-20170422-151159](https://cloud.githubusercontent.com/assets/5328644/25305803/69f7a980-2782-11e7-8879-e4a2e51fdcf2.png)
# 64cn
![064-msg0000001b-nr01000-it00010-20170422-170656](https://cloud.githubusercontent.com/assets/5328644/25305805/6a18eac8-2782-11e7-92ca-f6bccd5cd95e.png)
# 128cn
![128-msg0000001b-nr01000-it00010-20170422-170929](https://cloud.githubusercontent.com/assets/5328644/25305804/6a145e4a-2782-11e7-8412-16b4016e277a.png)
# 256cn
![256-msg0000001b-nr01000-it00010-20170422-171540](https://cloud.githubusercontent.com/assets/5328644/25305806/6a1a82f2-2782-11e7-9f35-d7993fb427cd.png)
