### ISSUE TITLE
long description in setup.py should be put in place

### ISSUE THREAD

**Issue by boegel** [hpcugent/mympingpong#4]
otherwise https://pypi.python.org/pypi/mympingpong is kind of empty

**Comment by stdweird** [comment]
it's on my todo list for `shared_setup`

**Comment by JensTimmerman** [comment]
lots of people try to open 'Readme.md' (or .txt ) here and put this content in the long description, would this be possible for shared_setup ?

**Comment by stdweird** [comment]
@JensTimmerman already done in https://github.com/hpcugent/vsc-install/pull/6 for `README.md`

**Comment by JensTimmerman** [comment]
great!

**Comment by wpoely86** [comment]
Can be closed?
